# Generated by Django 4.0.3 on 2023-04-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='href',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='employee_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
