# Generated by Django 4.0.3 on 2023-04-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_automobilevo_href_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='href',
            new_name='import_href',
        ),
    ]
