# Generated by Django 4.0.3 on 2023-04-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicians',
            name='employee_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
