# Generated by Django 4.0.3 on 2023-04-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_technicians_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
        migrations.AlterField(
            model_name='technicians',
            name='employee_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
