# Generated by Django 4.0.3 on 2023-04-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='sold',
        ),
    ]
