# Generated by Django 4.0.3 on 2023-04-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_automobilevo_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='sold',
        ),
    ]
